#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — ADR-0037: get Fly.io and Turso accounts + CLIs ready. This wizard
# stops short of `fly launch`/`fly deploy`/volume creation and any Vercel env
# writes — those come once the Fly deployment config and the Turso client
# swap exist in the codebase. This is just: accounts exist, CLIs are
# authenticated, one Turso database exists, and you have its credentials in
# hand to paste in later.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "Trip Kraken hosting setup — Fly.io + Turso"

# Fly's CLI binary installs as `flyctl`, symlinked to `fly` — prefer whichever
# is already on PATH so a re-run doesn't care which name a prior install used.
FLY_BIN=""
if command -v fly >/dev/null 2>&1; then FLY_BIN="fly"
elif command -v flyctl >/dev/null 2>&1; then FLY_BIN="flyctl"
fi

# ── Stage 1: flyctl installed ───────────────────────────────────────────────
stage "Fly.io — install the CLI"
if [[ -n "$FLY_BIN" ]]; then
  say "flyctl is already installed ($($FLY_BIN version 2>/dev/null | head -n1))."
else
  say "No Fly CLI found. Install it, then re-run this wizard."
  step "Homebrew (recommended on macOS): brew install flyctl"
  note "or: curl -L https://fly.io/install.sh | sh"
  if command -v brew >/dev/null 2>&1 && confirm "Run 'brew install flyctl' now?"; then
    if brew install flyctl; then
      FLY_BIN="fly"
    else
      warn "brew install failed — install flyctl yourself, then re-run this script"
      SKIPPED+=("install flyctl")
    fi
  else
    warn "install it yourself, then re-run this script"
    SKIPPED+=("install flyctl")
  fi
fi

# ── Stage 2: Fly account + login ────────────────────────────────────────────
stage "Fly.io — create an account and log in"
if [[ -n "$FLY_BIN" ]] && "$FLY_BIN" auth whoami >/dev/null 2>&1; then
  say "Already logged in as $($FLY_BIN auth whoami 2>/dev/null)."
else
  say "If you don't have a Fly.io account yet, sign up first."
  open_url "https://fly.io/app/sign-up"
  pause "Signed up (or already have an account)? Press Enter to continue."
  if [[ -n "$FLY_BIN" ]]; then
    say "Running '$FLY_BIN auth login' — this opens a browser to finish login."
    "$FLY_BIN" auth login || warn "login didn't complete — re-run this script to retry"
  else
    SKIPPED+=("fly auth login — flyctl isn't installed yet")
  fi
fi

# ── Stage 3: Fly payment method ─────────────────────────────────────────────
stage "Fly.io — add a payment method"
say "Fly requires a card on file before it will create Machines or Volumes,"
say "even for the small, scale-to-zero usage this project needs (ADR-0037)."
open_url "https://fly.io/dashboard/personal/billing"
step "Add a payment method if the billing page shows none yet."
pause "Done? Press Enter to continue."

# Turso's CLI binary is `turso`.
TURSO_BIN=""
command -v turso >/dev/null 2>&1 && TURSO_BIN="turso"

# ── Stage 4: turso CLI installed ────────────────────────────────────────────
stage "Turso — install the CLI"
if [[ -n "$TURSO_BIN" ]]; then
  say "turso CLI is already installed ($(turso --version 2>/dev/null))."
else
  say "No Turso CLI found. Install it, then re-run this wizard."
  step "Homebrew (recommended on macOS): brew install tursodatabase/tap/turso"
  note "or: curl -sSfL https://get.tur.so/install.sh | bash"
  if command -v brew >/dev/null 2>&1 && confirm "Run 'brew install tursodatabase/tap/turso' now?"; then
    if brew install tursodatabase/tap/turso; then
      TURSO_BIN="turso"
    else
      warn "brew install failed — install the turso CLI yourself, then re-run this script"
      SKIPPED+=("install turso CLI")
    fi
  else
    warn "install it yourself, then re-run this script"
    SKIPPED+=("install turso CLI")
  fi
fi

# ── Stage 5: Turso account + login ──────────────────────────────────────────
stage "Turso — create an account and log in"
if [[ -n "$TURSO_BIN" ]] && turso auth whoami >/dev/null 2>&1; then
  say "Already logged in as $(turso auth whoami 2>/dev/null)."
else
  say "'turso auth login' opens a browser; it creates an account for you on"
  say "first login if you don't already have one."
  if [[ -n "$TURSO_BIN" ]]; then
    turso auth login || warn "login didn't complete — re-run this script to retry"
  else
    SKIPPED+=("turso auth login — turso CLI isn't installed yet")
  fi
fi

# ── Stage 6: create the database, surface its credentials ──────────────────
stage "Turso — create the database"
DB_NAME="trip-kraken"
if [[ -n "$TURSO_BIN" ]]; then
  if turso db show "$DB_NAME" >/dev/null 2>&1; then
    say "Database '$DB_NAME' already exists — reusing it."
  elif ! turso db create "$DB_NAME"; then
    warn "couldn't create database '$DB_NAME' — check the error above and re-run"
    SKIPPED+=("turso db create $DB_NAME")
  fi

  DB_URL=$(turso db show "$DB_NAME" --url 2>/dev/null || true)
  DB_TOKEN=$(turso db tokens create "$DB_NAME" 2>/dev/null || true)

  printf '\n'
  say "Copy these two values somewhere safe now — they go into Vercel's env"
  say "vars and your local .env.local once the Turso client swap lands in"
  say "the app. This wizard does not write them to any file itself."
  printf '\n'
  printf '  %sTURSO_DATABASE_URL%s=%s\n' "$BOLD" "$RESET" "$DB_URL"
  printf '  %sTURSO_AUTH_TOKEN%s=%s\n' "$BOLD" "$RESET" "$DB_TOKEN"
  printf '\n'
  pause "Copied both values? Press Enter to continue."
else
  warn "turso CLI isn't installed — can't create the database yet"
  SKIPPED+=("turso db create $DB_NAME (needs the turso CLI)")
fi

finish

note "Accounts and CLIs are ready. Next: the Fly deployment config for"
note "VROOM/OSRM and the Turso client/schema swap land in the codebase —"
note "that part's Claude's job, not another manual stage."
